# -*- coding: utf-8 -*-
"""App. of ML Lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGPJuImNb65sVZasQBiRPag1szrjbioi

# LAB 1
**Implement and demonstrate the FIND S algorithm for finding the most specific hypothesis based on a given set of training data samples. Read the training data from a .csv file.**
"""

import pandas as pd
import numpy as np

d1 = pd.read_csv("/content/weather.csv")
d1

import csv
a = []
with open('/content/weather.csv', 'r') as csvfile:
 for row in csv.reader(csvfile):
   a.append(row)
print(a)

num_attribute = len(a[0])-1

print("\n The total number of training instances are : ",len(a))

num_attribute = len(a[0])-1
num_attribute

print("\n The initial hypothesis is : ")
hypothesis = ['0']*num_attribute
print(hypothesis)

for i in range(0, len(a)):
  if a[i][num_attribute] == 'yes':
    for j in range(0, num_attribute):
      if hypothesis[j] == '0' or hypothesis[j] == a[i][j]:
        hypothesis[j] = a[i][j]
      else:
        hypothesis[j] = '?'
  print("\n The hypothesis for the training instance {} is :\n" .format(i+1),hypothesis)

print("The Maximally specific hypothesis for the training instance is - ")
print(hypothesis)